calls/urls.py
# coding: UTF-8
from django.urls import path

app_name = 'calls'
urlpatterns = [
  
]

intranet_phonecenter/urls.py
from django.contrib import admin
from django.urls import path, include
import users
import customer
import credits
import calls
import supports

admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls', namespace='users')),
    path(r'customer/', include('customer.urls', namespace='customer')),
    path(r'credits/', include('credits.urls', namespace='credits')),
    path(r'calls/', include('calls.urls', namespace='calls')),
    path(r'supports/', include('supports.urls', namespace='supports')),
]

users/urls.py
# coding: UTF-8
from django.urls import path
from users import views

app_name = 'users'
urlpatterns = [
  path('hello/', views.hello, name="hello"),
  path('register/', views.register, name="register"),
  path('logout/', views.logout_view, name="logout"),
  path('login/', views.login_view, name="login"),
  path('myaccount/', views.myaccount, name="myaccount"),
  path('account-settings/', views.account_settings, name="account_settings"),
]

intranet_phonecenter/templates/base.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Intranet-Phonecenter{% endblock title %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    {% load static %}
    <script src="{% static 'js/base.js' %}"></script>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

    {% block head_end %}{% endblock head_end %}
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">IntranetPhonecenter</a>

      {% if request.user.is_superuser %}
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a href="{% url 'admin:index' %}" class="nav-link"> Admin Django</a>
          </li>
        </ul>
      {% endif %}
      {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:logout' %}">Déconnexion</a>
          </li>
        </ul>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:myaccount' %}">{{ user.get_username }}</a>
          </li>
        </ul>
      {% else %}
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:login' %}">Connexion</a>
          </li>
        </ul>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:register' %}">Inscription</a>
          </li>
        </ul>
      {% endif %}
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">

      </div>
    </nav>

    {% block body_header %}{% endblock body_header %}
    <main role="main" class="container" style="padding-top:60px;">

      <div class="starter-template">
        {% block content %}{% endblock content %}
      </div>

    </main>

    {% block body_footer %}{% endblock body_footer %}

  </body>
</html>